### ISSUE TITLE
 Reporte por date no trae las fechas ordenadas cronologicamente

### ISSUE THREAD

**Issue by ernestosperanza** [ORT-FIS-202108/proyecto-6-caraballo-lopez-speranza#59]
**Resumen**: El reporte por date no trae las fechas ordenadas cronologicamente
**Plataforma**: Web. Todas las versiones.
**Severidad**: Medio
**Prioridad**: Media
**Pasos a reproducir**:
Abrir navegador web
Loguearse con el usuario de prueba (user:test@test.com pass: 12345678)
ir a ver reporte
seleccionar reporte por fecha
**Resultado actual**: El reporte por fecha no se genera en orden cronologico
**Resultado esperado**: Reporte por fecha en orden cronologico
**Adjunto**: 
![image](https://user-images.githubusercontent.com/29267672/142768163-0677248b-9d12-4339-b80d-9dabcda33e00.png)

**Comment by ernestosperanza** [comment]
Diego te asigno el issue para que lo revises en el caso que tengamos tiempo, gracias!

**Comment by csdiego** [comment]
Se resuelve este issue, ordenando por fecha, el fix esta en la rama 63-bug_fix-diego_caraballo-issue_fechas_graficas_#59
