### ISSUE TITLE
Clase objeto Category queda obsoleta

### ISSUE THREAD

**Issue by FL209003** [ORT-FIS-202108/proyecto-6-caraballo-lopez-speranza#63]
Resumen: Clase objeto Category queda obsoleta
Plataforma: Web. Todas las versiones.
Severidad: Media
Prioridad: Media
Pasos a reproducir:
Ninguno
Adjunto: ninguno
Comentario: TODO: Eliminar Category.js de dominio y comprobar que todo continua funcionando de forma correcta.

**Comment by ernestosperanza** [comment]
Quedo removida la clase en el branch 59-enhancement-ernesto_spernaza-issue#63
